// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Firebase is only configured for Android and Web platforms. '
          'iOS, macOS, Windows, and Linux are not supported.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByc3semPSqGPBbylhhqKQlUS1i5AbZoS0',
    appId: '1:373324545697:web:cc9d3c285576381f47bae0',
    messagingSenderId: '373324545697',
    projectId: 'voice-call-138a1',
    authDomain: 'voice-call-138a1.firebaseapp.com',
    storageBucket: 'voice-call-138a1.firebasestorage.app',
    measurementId: 'G-Q0EMRL70ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWb9ecWXJD3JpMNEkRy02wqKPk0rFp7EU',
    appId: '1:373324545697:android:a9bef4de015eff6247bae0',
    messagingSenderId: '373324545697',
    projectId: 'voice-call-138a1',
    storageBucket: 'voice-call-138a1.firebasestorage.app',
  );
}